name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmake-version: [ '3.24' ]

    steps:
    - uses: actions/checkout@v4
    - name: Set Up CMake
      uses: actions/checkout@v1
    - name: Configure CMake
      run: cmake -S . -B build
    - name: build
      run: cmake --build build
    - name: Run tests
      run: cmake --build build --target test

    - name: Run Google Test cases and generate XML report
            cd TEST_CPPDiveDeep
      run: build/TEST_CPPDiveDeep/./test --gtest_output=xml:test_results.xml
 
    - name: Save test results
      uses: actions/checkout@v4
      with:
        name: test-results
        path: build/TEST_CPPDiveDeep/test_results.xml